<a href="https://colab.research.google.com/github/SH22Hwang/GNU_AugumentedIntelligenceLab/blob/main/ch3_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SH22Hwang 황승현

- 으뜸 머신러닝 3장 심화문제 

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr = np.random.randint(10, size=(10000, 10000))
print(arr, arr.shape)

[[5 4 4 ... 4 1 9]
 [2 4 8 ... 1 2 2]
 [0 2 3 ... 2 1 0]
 ...
 [7 5 6 ... 5 4 4]
 [9 4 6 ... 5 3 3]
 [9 1 8 ... 2 1 8]] (10000, 10000)


In [ ]:
arr1 = arr + 1
arr1

array([[ 6,  5,  5, ...,  5,  2, 10],
       [ 3,  5,  9, ...,  2,  3,  3],
       [ 1,  3,  4, ...,  3,  2,  1],
       ...,
       [ 8,  6,  7, ...,  6,  5,  5],
       [10,  5,  7, ...,  6,  4,  4],
       [10,  2,  9, ...,  3,  2,  9]])

In [ ]:
arr2 = arr.copy()
arr2[::2, :10000] = 0 # 0부터 9999까지 한 개씩 건너뛰어(step=2) 0
arr2

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 4, 8, ..., 1, 2, 2],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 5, 6, ..., 5, 4, 4],
       [0, 0, 0, ..., 0, 0, 0],
       [9, 1, 8, ..., 2, 1, 8]])

In [ ]:
arr3 = arr2.copy()
arr3[:10000, 1::2] = 0
arr3

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 0, 8, ..., 0, 2, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 6, ..., 0, 4, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [9, 0, 8, ..., 0, 1, 0]])

In [ ]:
name_s = pd.Series(['A', 'B', 'C', 'D', 'E', 'F', 'G'])
horsePower_s = pd.Series([130, 250, 190, 300, 210, 220, 170])
weight_s = pd.Series([1.9, 2.6, 2.2, 2.9, 2.4, 2.3, 2.2])
efficiency_s = pd.Series([16.3, 10.2, 11.1, 7.1, 12.1, 13.2, 14.2])

df = pd.DataFrame({'name': name_s, 'horse power': horsePower_s, 'weight': weight_s, 'efficiency': efficiency_s})
df

name  horse power  weight  efficiency
0    A          130     1.9        16.3
1    B          250     2.6        10.2
2    C          190     2.2        11.1
3    D          300     2.9         7.1
4    E          210     2.4        12.1
5    F          220     2.3        13.2
6    G          170     2.2        14.2

In [ ]:
df2 = df.set_index('name')
df2

horse power  weight  efficiency
name                                 
A             130     1.9        16.3
B             250     2.6        10.2
C             190     2.2        11.1
D             300     2.9         7.1
E             210     2.4        12.1
F             220     2.3        13.2
G             170     2.2        14.2

In [ ]:
df2['grade'] = df2['horse power'] * df2['efficiency']
df2

horse power  weight  efficiency   grade
name                                         
A             130     1.9        16.3  2119.0
B             250     2.6        10.2  2550.0
C             190     2.2        11.1  2109.0
D             300     2.9         7.1  2130.0
E             210     2.4        12.1  2541.0
F             220     2.3        13.2  2904.0
G             170     2.2        14.2  2414.0

In [ ]:
print("마력과 연비를 곱한 값중 최대 값을 가진 차종:", df2[df2['grade'] == df2['grade'].max()].index[0])

마력과 연비를 곱한 값중 최대 값을 가진 차종: F
