<a href="https://colab.research.google.com/github/SH22Hwang/GNU_AugumentedIntelligenceLab/blob/main/eunsun/chap03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import copy

arr = np.random.randint(0,9,(10000,10000))
print("3.1")
print(arr)

arr1 = arr + 1
print("3.1.1")
print(arr1)

arr2  = copy.deepcopy(arr)
arr2[0::2] = 0
print("3.1.2")
print(arr2)

arr3 = copy.deepcopy(arr)
arr3[1::2] = 0
print("3.1.3")
print(arr3)

3.1
[[2 4 5 ... 5 0 7]
 [7 6 3 ... 0 5 4]
 [1 7 2 ... 0 0 7]
 ...
 [0 0 6 ... 1 7 2]
 [3 0 7 ... 3 8 8]
 [4 8 2 ... 8 8 6]]
3.1.1
[[3 5 6 ... 6 1 8]
 [8 7 4 ... 1 6 5]
 [2 8 3 ... 1 1 8]
 ...
 [1 1 7 ... 2 8 3]
 [4 1 8 ... 4 9 9]
 [5 9 3 ... 9 9 7]]
3.1.2
[[0 0 0 ... 0 0 0]
 [7 6 3 ... 0 5 4]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 6 ... 1 7 2]
 [0 0 0 ... 0 0 0]
 [4 8 2 ... 8 8 6]]
3.1.3
[[2 4 5 ... 5 0 7]
 [0 0 0 ... 0 0 0]
 [1 7 2 ... 0 0 7]
 ...
 [0 0 0 ... 0 0 0]
 [3 0 7 ... 3 8 8]
 [0 0 0 ... 0 0 0]]


In [ ]:
import numpy as np
import pandas as pd
name_series = pd.Series(['A','B','C','D','E','F','G'])
horse_power_series = pd.Series([130,250,190,300,210,220,170])
weight_series = pd.Series([1.9,2.6,2.2,2.9,2.4,2.3,2.2])
efficiency_series = pd.Series([16.3, 10.2, 11.1, 7.1, 12.1, 13.2, 14.2])

df = pd.DataFrame({'name':name_series, 'horse power':horse_power_series, 'weight':weight_series,'efficiency': efficiency_series})
print(df)

df = df.set_index("name")
print(df)

print(horse_power_series)
print(efficiency_series)
#df['choice'] = horse_power_series * efficiency_series

print(df)



print("마력과 연비를 곱한 값 중 최대 값을 가진 차종", df[df['choice'] == df['choice'].max()].index[0])

  name  horse power  weight  efficiency
0    A          130     1.9        16.3
1    B          250     2.6        10.2
2    C          190     2.2        11.1
3    D          300     2.9         7.1
4    E          210     2.4        12.1
5    F          220     2.3        13.2
6    G          170     2.2        14.2
      horse power  weight  efficiency
name                                 
A             130     1.9        16.3
B             250     2.6        10.2
C             190     2.2        11.1
D             300     2.9         7.1
E             210     2.4        12.1
F             220     2.3        13.2
G             170     2.2        14.2
0    130
1    250
2    190
3    300
4    210
5    220
6    170
dtype: int64
0    16.3
1    10.2
2    11.1
3     7.1
4    12.1
5    13.2
6    14.2
dtype: float64
      horse power  weight  efficiency
name                                 
A             130     1.9        16.3
B             250     2.6        10.2
C             190     2.2

KeyError: ignored